#!/usr/bin/env python3
"""
Generate the Android Vulkan dispatch shim (vk_android_loader.h/.cpp).

WHY THIS EXISTS
    Upstream RPCS3 includes <vulkan/vulkan.h> with prototypes enabled, so every
    vkFoo() call is a direct reference resolved against the system libvulkan.so
    at link time. There is no seam for a user-supplied driver -- and an APK
    cannot shadow libvulkan.so either, because it lives in the linker's
    public-library namespace.

    So on Android we build with VK_NO_PROTOTYPES and declare a function POINTER
    named after each function. Call sites are untouched: `vkCreateImage(...)`
    becomes a call through a pointer instead of a PLT entry. This is what volk
    does; we generate instead of vendoring volk so the table is exactly the set
    we import -- nothing to keep in sync, and no unused entry point that could
    sit null unnoticed.

    The core does NOT talk to adrenotools. The JNI glue (native-lib.cpp) opens
    the driver and hands the core a dlopen handle via _rpcsx_setCustomDriver,
    which keeps adrenotools app-side and out of the emulator.

REGENERATE
    llvm-nm -u libxeno-core.so | awk '{print $NF}' | grep ^vk | sort -u > syms.txt
    python3 android/tools/gen_vk_loader.py syms.txt
"""
import pathlib
import sys

syms = sorted({l.strip() for l in open(sys.argv[1]) if l.strip().startswith("vk")})
root = pathlib.Path(__file__).resolve().parents[2] / "rpcs3/Emu/RSX/VK"

BANNER = ("// GENERATED by android/tools/gen_vk_loader.py -- do not edit by hand.\n"
          "// See that script for why this shim exists.\n")

# ---------------------------------------------------------------- header

h = [BANNER, """#pragma once

#ifdef __ANDROID__

#include "VulkanAPI.h"

namespace vk::android
{
	// Point the dispatch table at an already-opened driver.
	//
	// The handle comes from the JNI glue, which is what calls adrenotools --
	// that keeps the dependency app-side and out of the emulator core. Pass
	// nullptr to fall back to the system libvulkan.so.
	//
	// Returns the PREVIOUS handle so the caller can dlclose it. The caller must
	// not do so while the old driver still owns live objects.
	void* set_driver_handle(void* handle);

	// Load the system driver if set_driver_handle() was never called. Safe to
	// call repeatedly and from any thread.
	bool ensure_loaded();

	// Re-resolve instance-level entry points once the VkInstance exists. Some
	// functions legitimately return null from vkGetInstanceProcAddr(nullptr, ..),
	// so the initial table has holes until this runs.
	void resolve_instance(VkInstance instance);

	// True when the table currently points at a user-supplied driver.
	bool using_custom_driver();

	// Human-readable reason the last load failed, or empty.
	const char* last_error();
}

extern "C"
{
"""]
h += [f"\textern PFN_{s} {s};\n" for s in syms]
h.append("}\n\n#endif // __ANDROID__\n")
(root / "vk_android_loader.h").write_text("".join(h))

# ---------------------------------------------------------------- source

c = [BANNER, """#include "stdafx.h"

#ifdef __ANDROID__

#include "vk_android_loader.h"
#include "util/logs.hpp"

#include <dlfcn.h>
#include <mutex>
#include <string>

LOG_CHANNEL(vk_loader);

extern "C"
{
"""]
c += [f"\tPFN_{s} {s} = nullptr;\n" for s in syms]
c.append("""}

namespace vk::android
{
	namespace
	{
		std::mutex g_mutex;
		void* g_handle = nullptr;
		bool g_custom = false;
		std::string g_error;

		// Resolve every entry point from `handle`.
		//
		// vkGetInstanceProcAddr comes from dlsym; everything else goes through IT
		// rather than dlsym, because a custom or layered driver may only expose
		// the rest via its loader entry point.
		//
		// Instance-level functions cannot resolve against a null instance, so they
		// stay null here and are filled in by resolve_instance() once the
		// VkInstance exists. dlsym is the fallback for both.
		bool resolve_all(void* handle)
		{
			vkGetInstanceProcAddr = reinterpret_cast<PFN_vkGetInstanceProcAddr>(
				dlsym(handle, "vkGetInstanceProcAddr"));

			if (!vkGetInstanceProcAddr)
			{
				g_error = "driver exports no vkGetInstanceProcAddr";
				return false;
			}

""")
for s in syms:
    if s == "vkGetInstanceProcAddr":
        continue
    c.append(f'\t\t\t{s} = reinterpret_cast<PFN_{s}>(vkGetInstanceProcAddr(nullptr, "{s}"));\n')
    c.append(f'\t\t\tif (!{s}) {s} = reinterpret_cast<PFN_{s}>(dlsym(handle, "{s}"));\n')
c.append("""
			if (!vkCreateInstance)
			{
				g_error = "driver exports no vkCreateInstance";
				return false;
			}

			return true;
		}
	}

	void resolve_instance(VkInstance instance)
	{
		if (!instance || !vkGetInstanceProcAddr) return;

""")
for s in syms:
    if s in ("vkGetInstanceProcAddr", "vkCreateInstance"):
        continue
    c.append(f'\t\tif (auto p = vkGetInstanceProcAddr(instance, "{s}")) {s} = reinterpret_cast<PFN_{s}>(p);\n')
c.append("""	}

	void* set_driver_handle(void* handle)
	{
		std::lock_guard lock(g_mutex);
		g_error.clear();

		void* previous = g_handle;

		if (!handle)
		{
			// Clearing the custom driver: fall back to the system one. Resolve now
			// rather than at next use, so a broken fallback is reported while
			// there is still a caller to report it to.
			handle = dlopen("libvulkan.so", RTLD_NOW | RTLD_LOCAL);
			g_custom = false;

			if (!handle)
			{
				const char* err = dlerror();
				g_error = err ? err : "libvulkan.so could not be opened";
				vk_loader.fatal("no Vulkan driver available: %s", g_error);
				return previous;
			}
		}
		else
		{
			g_custom = true;
		}

		if (!resolve_all(handle))
		{
			vk_loader.error("driver opened but unusable (%s); keeping the previous one", g_error);

			// Restore rather than leave the table half-resolved: a partially
			// populated table crashes on the first null entry, a long way from
			// the actual cause.
			g_custom = false;
			if (previous && resolve_all(previous))
			{
				// We went back to `previous`, so the caller must NOT close it.
				return nullptr;
			}

			return previous;
		}

		g_handle = handle;
		vk_loader.success("Vulkan driver bound (%s)", g_custom ? "custom" : "system");
		return previous;
	}

	bool ensure_loaded()
	{
		{
			std::lock_guard lock(g_mutex);
			if (g_handle) return true;
		}

		set_driver_handle(nullptr);

		std::lock_guard lock(g_mutex);
		return g_handle != nullptr;
	}

	bool using_custom_driver()
	{
		std::lock_guard lock(g_mutex);
		return g_custom;
	}

	const char* last_error()
	{
		std::lock_guard lock(g_mutex);
		return g_error.c_str();
	}
}

#endif // __ANDROID__
""")
(root / "vk_android_loader.cpp").write_text("".join(c))
print(f"generated {len(syms)} entry points")
